name: eis
channels:
  - defaults
dependencies:
  - bzip2=1.0.8 
  - ca-certificates=2022.2.1
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=21.2.4
  - python=3.10.0
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.37.2
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
      - aiohttp==3.8.1
      - aiohttp-retry==2.4.6
      - aiosignal==1.2.0
      - altair==4.2.0
      - anyio==3.5.0
      - appdirs==1.4.4
      - appnope==0.1.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==2.0.5
      - async-timeout==4.0.2
      - asyncssh==2.8.1
      - atpublic==3.0.1
      - attrs==21.4.0
      - babel==2.9.1
      - backcall==0.2.0
      - beautifulsoup4==4.10.0
      - bleach==4.1.0
      - cached-property==1.5.2
      - certifi==2021.10.8
      - cffi==1.15.0
      - charset-normalizer==2.0.12
      - colorama==0.4.4
      - commonmark==0.9.1
      - configobj==5.0.6
      - cryptography==36.0.2
      - cycler==0.11.0
      - debugpy==1.5.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dictdiffer==0.9.0
      - diskcache==5.4.0
      - distro==1.7.0
      - dpath==2.0.6
      - dulwich==0.20.34
      - dvc==2.9.5
      - entrypoints==0.4
      - executing==0.8.3
      - flake8==4.0.1
      - flatten-dict==0.4.2
      - flufl-lock==7.0
      - fonttools==4.30.0
      - frozenlist==1.3.0
      - fsspec==2022.2.0
      - ftfy==6.1.1
      - funcy==1.17
      - future==0.18.2
      - gitdb==4.0.9
      - gitpython==3.1.27
      - grandalf==0.6
      - idna==3.3
      - iniconfig==1.1.1
      - ipykernel==6.9.2
      - ipython==8.1.1
      - ipython-genutils==0.2.0
      - isort==5.10.1
      - jedi==0.18.1
      - jinja2==3.0.3
      - joblib==1.1.0
      - json5==0.9.6
      - jsonschema==4.4.0
      - jupyter-client==7.1.2
      - jupyter-core==4.9.2
      - jupyter-server==1.15.6
      - jupyterlab==3.3.2
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.11.2
      - kiwisolver==1.4.0
      - mailchecker==4.1.14
      - markupsafe==2.1.1
      - matplotlib==3.5.1
      - matplotlib-inline==0.1.3
      - mccabe==0.6.1
      - mistune==0.8.4
      - multidict==6.0.2
      - mypy==0.941
      - mypy-extensions==0.4.3
      - nanotime==0.5.2
      - nbclassic==0.3.7
      - nbclient==0.5.13
      - nbconvert==6.4.4
      - nbformat==5.2.0
      - nest-asyncio==1.5.4
      - networkx==2.7.1
      - notebook==6.4.10
      - notebook-shim==0.1.0
      - numpy==1.22.3
      - packaging==21.3
      - pandas==1.4.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.9.0
      - pexpect==4.8.0
      - phonenumbers==8.12.45
      - pickleshare==0.7.5
      - pillow==9.0.1
      - pluggy==1.0.0
      - ply==3.11
      - prometheus-client==0.13.1
      - prompt-toolkit==3.0.28
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py==1.11.0
      - pyasn1==0.4.8
      - pycodestyle==2.8.0
      - pycparser==2.21
      - pydot==1.4.2
      - pyflakes==2.4.0
      - pygit2==1.9.0
      - pygments==2.11.2
      - pygtrie==2.4.2
      - pyparsing==3.0.7
      - pyrsistent==0.18.1
      - pytest==7.1.0
      - python-benedict==0.25.0
      - python-dateutil==2.8.2
      - python-fsutil==0.6.0
      - python-slugify==6.1.1
      - pytz==2021.3
      - pyyaml==6.0
      - pyzmq==22.3.0
      - requests==2.27.1
      - rich==12.0.0
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.6
      - scikit-learn==1.0.2
      - scipy==1.8.0
      - scmrepo==0.0.7
      - send2trash==1.8.0
      - setuptools-scm==6.4.2
      - shortuuid==1.0.8
      - shtab==1.5.3
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.2.0
      - soupsieve==2.3.1
      - stack-data==0.2.0
      - tabulate==0.8.9
      - terminado==0.13.3
      - testpath==0.6.0
      - text-unidecode==1.3
      - threadpoolctl==3.1.0
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.11.2
      - tornado==6.1
      - tqdm==4.63.0
      - traitlets==5.1.1
      - typing-extensions==4.1.1
      - urllib3==1.26.9
      - voluptuous==0.12.2
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.3.1
      - xmltodict==0.12.0
      - yarl==1.7.2
      - zc-lockfile==2.0
