# an example pipeline

stages:
  test_train_split:
    cmd: python example_pipeline/stages/test_train_split.py
    deps:
      - train_data.csv
      - example_pipeline/stages/test_train_split.py
    outs:
      - example_pipeline/stage_data/train_data.csv
      - example_pipeline/stage_data/test_data.csv
  classify_ecms:
    cmd: python example_pipeline/stages/classifier.py
    deps:
      - example_pipeline/stage_data/train_data.csv
      - example_pipeline/stage_data/test_data.csv
      - example_pipeline/stages/classifier.py
    outs:
      - example_pipeline/stage_data/circuit_guesses.csv

  initial_parameters_guess:
    cmd: python example_pipeline/stages/parameter_guesser.py
    deps:
      - example_pipeline/stage_data/train_data.csv
      - example_pipeline/stage_data/circuit_guesses.csv
      - example_pipeline/stages/parameter_guesser.py
    outs:
      - example_pipeline/stage_data/submission.csv

  score:
    cmd: python example_pipeline/stages/score.py
    deps:
      - example_pipeline/stage_data/submission.csv
      - example_pipeline/stage_data/test_data.csv
      - example_pipeline/stages/score.py
    metrics:
      - example_pipeline/stage_data/metrics.json
